# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The JavaScripting English Major
description: A 15-session course that teaches humanities undergraduates how to write their own web-based project using JavaScript.
url: https://the-javascripting-english-major.org/
author: Moacir P. de Sá Pereira
twitter:
  username: jsingenglishmaj
logo: /apple-touch-icon.png
host-full: http://the-javascripting-english-major.org
exclude: 
 - screenshots
 - cheat_sheet
 - Gemfile
 - Gemfile.lock
 - README.md
 - CNAME
social:
  name: Moacir P. de Sá Pereira
  links:
    - https://github.com/muziejus
    - https://twitter.com/muziejus

# email: your-email@domain.com
# baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
# theme: jekyll-theme-leap-day
# baseurl: /javascripting-english-major
# theme: minima
# gems:
#   - jekyll-feed
# exclude:
#   - Gemfile
#   - Gemfile.lock
google-code: UA-592475-7
include: [ examples, v1]
kramdown:
  input: GFM
  auto_id_prefix: s-
  parse_block_html: true
  syntax_highlighter: rouge
  .syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
  chapters:
    output: true
  appendices:
    output: true
  help-pages:
    output: true
    permalink: /help/:name
defaults:
- scope:
    path: ""
    type: chapters
  values:
    layout: chapter
- scope:
    path: ""
    type: appendices
  values:
    layout: chapter
- scope:
    path: ""
    type: help-pages
  values:
    layout: help-page


